#pragma once

enum ScreenState {
    SCREEN_MAIN,
    SCREEN_SUBMENU,
    SCREEN_TOOL,
    SCREEN_SYSTEM_INFO,
    SCREEN_WIRELESS_UPDATE,
    SCREEN_SD_FORMAT_CONFIRM,
    SCREEN_FILE_MANAGER,
    SCREEN_FILE_DETAIL,
    SCREEN_FILE_DELETE_CONFIRM,
    SCREEN_FILE_RENAME,
    SCREEN_WIFI_DETAIL,
    SCREEN_BLE_DETAIL,
    SCREEN_EP_RENAME,
    SCREEN_STORAGE_SETTINGS
};

enum RadioMode : int {
    RADIO_IDLE,
    RADIO_24_SCAN,
    RADIO_NOISE_ANALYZER,
    RADIO_24_ACTIVE,
    RADIO_24_PROTOCOL_ANALYZER,
    RADIO_24_PACKET_FLOOD,

    RF_SCANNER,
    RF_MONITOR,
    RF_SIGNAL_CAPTURE,
    RF_FREQUENCY_SWEEP,
    RF_TRANSMIT,
    RF_JAMMER,
    RF_SQUELCH_ACTIVATE,

    WIFI_SCAN,
    WIFI_PACKET_MONITOR,
    WIFI_BEACON,
    WIFI_DETECTOR,
    WIFI_PROBE_SNIFF,
    WIFI_BEACON_SNIFF,
    WIFI_DEAUTH_SNIFF,
    WIFI_EAPOL_SCAN,
    WIFI_RAW_CAPTURE,
    WIFI_STATION_SNIFF,
    WIFI_SIGNAL_MONITOR,
    WIFI_CHANNEL_ANALYZER,
    WIFI_PACKET_COUNT,
    WIFI_SCAN_ALL,
    WIFI_ATTACK_EVIL_PORTAL,
    WIFI_ATTACK_RICKROLL,
    WIFI_ATTACK_PROBE_FLOOD,
    WIFI_ATTACK_DEAUTH_FLOOD,
    WIFI_ATTACK_AP_CLONE,

    BLE_SCAN,
    BLE_BEACON_SPAM,
    BLE_BEACON_TEST,
    BLE_DEVICE_STABLE,
    BLE_RADAR,
    BLE_SIGNAL_LOGGER_PICK,
    BLE_SIGNAL_LOGGER,
    
    // BLE Attacks
    BLE_ATTACK_SOUR_APPLE,
    BLE_ATTACK_SWIFTPAIR,
    BLE_ATTACK_SAMSUNG,
    BLE_ATTACK_BEACON_SPAM,
    BLE_ATTACK_SPAM_ALL,
    BLE_JAMMER,
    BLE_SPOOFER,
    BLE_RUBBER_DUCKY,
    
    // WiFi Advanced
    WIFI_CONNECT,
    WIFI_PING_SCAN,
    WIFI_ATTACK_BAD_MSG,
    WIFI_ATTACK_CHANNEL_SWITCH,
    WIFI_ATTACK_QUIET,
    WIFI_ATTACK_ASSOC_SLEEP,

    // New features
    WIFI_HIDDEN_SSID_REVEAL,   // Deauth + probe to reveal hidden SSIDs
    BLE_AIRTAG_SPOOF,          // Apple AirTag spoofer
    RF_ROLLING_CAPTURE,        // Rolling code capture (CC1101)
    RF_REPLAY                  // Direct OOK capture + replay
};
