import pathlib

HTML = []
def w(*args): HTML.extend(args)

# ── HEAD + STYLES ──────────────────────────────────────────────────────────
w("<!doctype html>","<html lang=en>","<head>",
"<meta charset=utf-8>",
"<meta name=viewport content=\"width=device-width,initial-scale=1\">",
    "<title>Skull Breaker Companion</title>",
"<style>",
"*{box-sizing:border-box;margin:0;padding:0}",
"body{font-family:Segoe UI,sans-serif;background:#0d1117;color:#e6edf3;height:100vh;display:flex;flex-direction:column;overflow:hidden}",
"header{padding:10px 18px;background:linear-gradient(135deg,#0f2a3a,#0a1f10);border-bottom:1px solid #21262d;display:flex;align-items:center;gap:14px;flex-shrink:0}",
"header h1{font-size:18px;font-weight:700}",
"#mode-display{font-size:12px;color:#8b949e;flex:1}",
"#conn-status{display:flex;align-items:center;gap:8px;font-size:13px}",
".dot{width:9px;height:9px;border-radius:50%;background:#3d4450;flex-shrink:0}",
".dot.on{background:#3fb950}",
"#port-btn{padding:5px 13px;border-radius:7px;border:1px solid #30363d;background:#161b22;color:#e6edf3;cursor:pointer;font-size:12px}",
"#port-btn:hover{background:#21262d}",
".layout{display:flex;flex:1;overflow:hidden}",
".sidebar{width:200px;background:#0d1117;border-right:1px solid #21262d;display:flex;flex-direction:column;flex-shrink:0}",
".status-bar{padding:10px;border-bottom:1px solid #21262d;font-size:12px}",
".srow{display:flex;justify-content:space-between;align-items:center;margin-bottom:5px}",
".badge{padding:1px 7px;border-radius:999px;font-size:11px;font-weight:600}",
".ok{background:#0d2818;color:#3fb950;border:1px solid #1a4a2a}",
".err{background:#2d1010;color:#f85149;border:1px solid #4a1a1a}",
".off{background:#1c2128;color:#8b949e;border:1px solid #30363d}",
".batt-row{display:flex;align-items:center;gap:6px;margin-top:6px}",
".batt-outer{width:36px;height:13px;border:1px solid #30363d;border-radius:3px;overflow:hidden}",
".batt-inner{height:100%;background:#3fb950;transition:width .3s}",
".batt-inner.low{background:#f85149}",
".batt-inner.mid{background:#d29922}",
"nav{flex:1;overflow-y:auto;padding:6px}",
".ni{padding:8px 10px;border-radius:7px;cursor:pointer;font-size:13px;color:#8b949e;display:flex;align-items:center;gap:7px;transition:all .12s;user-select:none}",
".ni:hover{background:#161b22;color:#e6edf3}",
".ni.active{background:#1f3a2a;color:#3fb950}",
".dpad{padding:10px;border-top:1px solid #21262d}",
".dpad-lbl{font-size:10px;color:#8b949e;text-align:center;margin-bottom:6px;text-transform:uppercase;letter-spacing:.5px}",
".dpad-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:3px;max-width:108px;margin:0 auto}",
".db{padding:7px;border-radius:6px;border:1px solid #30363d;background:#161b22;color:#e6edf3;cursor:pointer;font-size:13px;text-align:center;user-select:none;-webkit-tap-highlight-color:transparent}",
".db:active,.db.held{background:#1f3a2a;border-color:#3fb950;color:#3fb950}",
".db.ctr{background:#1a2a3a;border-color:#1f6feb}",
".main{flex:1;display:flex;flex-direction:column;overflow:hidden;position:relative}",
".tabs{display:flex;border-bottom:1px solid #21262d;background:#0d1117;flex-shrink:0;overflow-x:auto}",
".tab{padding:9px 16px;font-size:12px;cursor:pointer;color:#8b949e;border-bottom:2px solid transparent;white-space:nowrap;user-select:none}",
".tab:hover{color:#e6edf3}",
".tab.active{color:#58a6ff;border-bottom-color:#58a6ff}",
".panels{flex:1;overflow:hidden;position:relative}",
".panel{position:absolute;inset:0;overflow-y:auto;padding:14px;display:none}",
".panel.active{display:block}",
"#no-serial{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:14px;color:#8b949e;text-align:center;padding:40px;background:#0d1117;z-index:20}",
"#no-serial h2{font-size:17px;color:#e6edf3}",
".card{background:#161b22;border:1px solid #21262d;border-radius:9px;padding:12px;margin-bottom:10px}",
".ctitle{font-size:13px;font-weight:600;margin-bottom:9px;color:#e6edf3}",
".sec{font-size:10px;font-weight:600;color:#8b949e;text-transform:uppercase;letter-spacing:.7px;margin-bottom:8px}",
".toolbar{display:flex;gap:7px;margin-bottom:10px;flex-wrap:wrap;align-items:center}",
".mbadge{padding:3px 9px;border-radius:999px;background:#1f3a2a;color:#3fb950;font-size:11px;font-weight:600;border:1px solid #1a4a2a}",
".btn{padding:6px 13px;border-radius:7px;border:none;background:#1f6feb;color:#fff;cursor:pointer;font-size:12px;font-weight:600}",
".btn:hover{background:#388bfd}",
".btn.s{background:#21262d;border:1px solid #30363d;color:#e6edf3}",
".btn.s:hover{background:#2d333b}",
".screen-wrap{display:flex;gap:14px;flex-wrap:wrap}",
".screen-box{background:#000;border:2px solid #30363d;border-radius:8px;padding:10px;font-family:Consolas,monospace;font-size:12px;min-width:260px;flex:1;max-width:380px}",
".screen-title{color:#58a6ff;font-size:11px;margin-bottom:6px;text-transform:uppercase;letter-spacing:.5px}",
".screen-line{padding:2px 4px;border-radius:3px;color:#c9d1d9;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}",
".screen-line.sel{background:#1f3a2a;color:#3fb950}",
".screen-line.dim{color:#484f58}",
".screen-info{flex:1;min-width:200px}",
".dlist{display:flex;flex-direction:column;gap:3px}",
".drow{display:flex;align-items:center;gap:8px;padding:7px 9px;border-radius:7px;cursor:pointer;font-size:12px}",
".drow:hover{background:#1c2128}",
".drow.sel{background:#1f3a2a;border:1px solid #1a4a2a}",
".dname{flex:1;font-weight:500}",
".dmeta{color:#8b949e;font-size:11px}",
".rbar{width:44px;height:5px;border-radius:3px;background:#21262d;overflow:hidden;flex-shrink:0}",
".rfill{height:100%;border-radius:3px;background:#3fb950;transition:width .3s}",
".rfill.mid{background:#d29922}",
".rfill.weak{background:#f85149}",
".dgrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}",
".ditem{background:#0d1117;border-radius:5px;padding:7px 9px}",
".dkey{font-size:10px;color:#8b949e;margin-bottom:2px}",
".dval{font-size:12px;font-weight:500;font-family:Consolas,monospace;word-break:break-all}",
".freq{font-size:26px;font-weight:700;font-family:Consolas,monospace;color:#58a6ff;text-align:center;padding:8px 0}",
".meter{display:flex;align-items:center;gap:8px;margin-bottom:6px}",
".mlbl{font-size:11px;color:#8b949e;width:36px}",
".mbar{flex:1;height:8px;background:#21262d;border-radius:4px;overflow:hidden}",
".mfill{height:100%;border-radius:4px;transition:width .2s}",
".mval{font-size:11px;font-family:Consolas,monospace;width:52px;text-align:right}",
"canvas{display:block;width:100%;border-radius:5px;background:#0d1117}",
".frow{display:flex;align-items:center;gap:7px;padding:6px 9px;border-radius:6px;cursor:pointer;font-size:12px}",
".frow:hover{background:#1c2128}",
".frow.sel{background:#1f3a2a}",
".ficon{font-size:14px;width:18px}",
".fname{flex:1}",
".fsize{color:#8b949e;font-size:11px}",
".pathbar{font-family:Consolas,monospace;font-size:11px;color:#8b949e;padding:5px 9px;background:#0d1117;border-radius:5px;margin-bottom:7px;word-break:break-all}",
".logbox{font-family:Consolas,monospace;font-size:11px;background:#0d1117;border:1px solid #21262d;border-radius:6px;padding:9px;overflow-y:auto;color:#8b949e;white-space:pre-wrap;word-break:break-all}",
".empty{text-align:center;padding:30px;color:#8b949e;font-size:13px}",
".two{display:grid;grid-template-columns:1fr 300px;gap:12px}",
".two2{display:grid;grid-template-columns:1fr 1fr;gap:12px}",
"@media(max-width:700px){.two,.two2{grid-template-columns:1fr}}",
"</style>","</head>","<body>")
